config/deploy.rb
config/deploy/staging.rb
lib/capistrano/tasks/restart.cap

Configure capistrano for further deployments

Configure capistrano for deployments

---

lib/tasks/budgets.rake
lib/tasks/migrations.rake

- Delete all drafting phases after updating the budgets in draft mode
- Fix rake that was not correctly updating the name of the phases

Ajust rakes for budget migration

---

app/helpers/budgets_helper.rb
app/views/admin/budgets/_form.html.erb
spec/features/admin/budgets_spec.rb

Show only enabled phases in budget phase selector

Show only enabled phases in budget phase selector

---

app/assets/stylesheets/custom.scss
app/views/budgets/investments/_actions.html.erb
app/views/comments/_actions.html.erb
app/views/debates/_actions.html.erb
app/views/legislation/proposals/_actions.html.erb
app/views/proposal_notifications/_actions.html.erb
app/views/proposals/_actions.html.erb
app/views/users/registrations/new.html.erb
config/locales/custom/en/admin.yml
config/locales/custom/nl/admin.yml
config/locales/custom/nl/budgets.yml
config/locales/custom/nl/devise.yml
config/locales/custom/nl/devise_views.yml
config/locales/custom/nl/general.yml
config/locales/custom/nl/legislation.yml
config/locales/custom/nl/mailers.yml
config/locales/custom/nl/responders.yml
spec/features/admin/activity_spec.rb
spec/features/debates_spec.rb

- Add new message to confirm moderation actions.
- Update email for Groningen
- Fix link to register a new account as an organization
- Show each poll answer in a new line

Customization Groningen

---

config/locales/custom/nl/legislation.yml

Custom translations

---

lib/tasks/budgets.rake

Adjust rake for after applying budgets improvements

Adjust rake for after applying budgets improvements

---

config/initializers/errbit.rb

Ignore more not real errors in errbit

Ignore more not real errors in errbit

---

config/locales/custom/nl/general.yml

Add custom translation

---

app/views/budgets/_budget.html.erb
config/locales/custom/nl/budgets.yml

- Update custom translations for budgets

Update custom translations for budgets

---

app/views/custom/layouts/_footer.html.erb
config/locales/custom/en/general.yml
config/locales/custom/nl/general.yml

Remove facebook link on custom footer.

Remove facebook link on custom footer

---

app/assets/stylesheets/custom.scss
app/views/custom/welcome/_processes.html.erb
app/views/welcome/index.html.erb
config/locales/custom/nl/general.yml
spec/features/admin/homepage/homepage_spec.rb

Add custom styles to welcome processes feed.

Add custom styles to welcome processes feed

---

app/views/mailer/budget_investment_created.html.erb
config/locales/custom/nl/devise.yml
config/locales/custom/nl/legislation.yml
config/locales/custom/nl/mailers.yml

Custom content

---

app/views/budgets/_phases.html.erb

- Add custom video on the first budget phase.

Add custom video on first budget phase

---

app/views/budgets/_phases.html.erb

Add missing title and alt on budget phase images.

Add missing title and alt on budget phase images

---

app/views/budgets/_phases.html.erb
config/locales/custom/nl/activerecord.yml
config/locales/custom/nl/admin.yml
config/locales/custom/nl/devise_views.yml
config/locales/custom/nl/responders.yml

- Replace the budget phase custom video.
- Update custom texts.

Custom video and texts

---

config/locales/custom/nl/devise_views.yml

Adjust custom translation

---

app/views/budgets/_phases.html.erb

- Replace custom video on the budget phase.

Replace custom video on budget phase

---

app/views/budgets/_phases.html.erb

- Move custom video to the second phase.

Move custom video to the second phase

---

app/views/budgets/_phases.html.erb

Update custom video

---

spec/features/debates_spec.rb
spec/features/legislation/processes_spec.rb
spec/features/polls/polls_spec.rb

Fix some flaky specs that we have detected

Fix flaky specs

---

config/locales/custom/nl/budgets.yml

- Replace custom text on budget investment new recommendations.

Replace custom text on budget investment new recommendations

---

app/views/mailer/newsletter.html.erb

- Replace autolink to sanitize on mailer newsletter.

Replace autolink to sanitize on mailer newsletter

---

config/locales/custom/en/admin.yml
config/locales/custom/nl/admin.yml
config/secrets.yml.example
lib/user_segments.rb
spec/features/admin/emails/newsletters_spec.rb
spec/lib/user_segments_spec.rb

- Add beta testers user segment.

Add beta testers user segment

---

app/views/legislation/processes/_header_full.html.erb

- Fix id for additional info process button.

Fix id for additional info process button

---

app/assets/stylesheets/custom.scss
app/views/admin/newsletters/_form.html.erb
app/views/mailer/newsletter.html.erb
spec/features/admin/emails/newsletters_spec.rb

- Add admin options to newsletter form.
- Improve newsletter styles.

Newsletter

---

app/assets/javascripts/moderator_comment.js
app/assets/stylesheets/custom.scss
app/controllers/comments_controller.rb
app/helpers/comments_helper.rb
app/models/abilities/common.rb
app/models/abilities/moderation.rb
app/views/comments/_actions.html.erb
app/views/comments/_comment.html.erb
app/views/comments/hide.js.erb
config/locales/custom/en/general.yml
config/locales/custom/nl/general.yml
config/routes/comment.rb
spec/features/comments/debates_spec.rb
spec/models/abilities/moderator_spec.rb

- Allow users to delete their own comments.

Allow users to delete their own comments

---

config/locales/custom/nl/devise.yml

- Replace equal password error message.

Replace equal password error message

---

app/views/budgets/investments/index.html.erb
config/locales/custom/nl/budgets.yml
config/locales/en/budgets.yml

- Remove unfeasible text on budget investments index.

Remove unfeasible text on budget investments index

---

app/assets/stylesheets/custom.scss

- Fix read more link position on budget investment index list.

Fix read more link position on budget investment index list

---

config/locales/custom/nl/mailers.yml

- Replace budget investment unfeasible subject email.

Replace budget investment unfeasible subject email

---

app/views/budgets/_phases.html.erb

Show custom video only in "Groene parel" budget.

Custom budget video

---

app/controllers/admin/budgets_controller.rb
config/locales/en/admin.yml
config/locales/es/admin.yml
spec/features/admin/budgets_spec.rb

Allow deleting a budget with a poll associated

Allow deleting a budget with a poll associated

---

config/locales/custom/nl/budgets.yml

Replace custom support title text.

Replace custom support title text

---

app/assets/stylesheets/custom.scss
app/views/welcome/_cards.html.erb

Fix homepage cards layout

---

app/controllers/valuation/budget_investments_controller.rb
app/controllers/valuation/budgets_controller.rb
app/views/valuation/budgets/index.html.erb
spec/features/admin/budget_investments_spec.rb
spec/features/valuation/budget_investments_spec.rb
spec/features/valuation/budgets_spec.rb

Show all budgets in valuating phase on valuation panel.

Show all budgets in valuating phase on valuation panel

---

app/views/budgets/_budget.html.erb
spec/features/budgets/budgets_spec.rb

Show custom phase name on budget subheader.

Show custom phase name on budget subheader

---

app/controllers/admin/budgets_controller.rb
spec/features/admin/budgets_spec.rb

Load correctly the list of administrators and valuators after updating a budget.

Correct load administrator and valuator list for budgets

---

app/assets/stylesheets/custom.scss

Fix legislation comments box container position.

Fix legislation comments box container position

---

app/views/budgets/ballot/_ballot.html.erb
spec/features/budgets/ballots_spec.rb

Replace back link to corresponding budget instead of `budgets_path`.

Replace back link to corresponding budget

---

app/views/budgets/results/_results_table.html.erb

Fix table size on budget results.

Fix table size on budget results

---

config/locales/custom/nl/mailers.yml

Update budget investment unfeasible subject.

Update budget investment unfeasible subject

---

app/views/custom/polls/_poll_group.html.erb
spec/features/polls/polls_spec.rb

Hide remaining days message on expired polls.

Hide remaining days message on expired polls

---

app/views/polls/results.html.erb

Change polls results table layout.

Change polls results table layout

---

app/helpers/legislation_helper.rb
app/models/legislation/process/phase.rb
app/models/legislation/process/publication.rb
app/views/custom/legislation/processes/_key_dates.html.erb
app/views/custom/legislation/processes/_phase_status.html.erb
app/views/custom/legislation/processes/_process.html.erb
app/views/legislation/processes/_key_dates.html.erb
app/views/legislation/processes/_phase_dates.html.erb
app/views/legislation/processes/_process.html.erb
spec/system/legislation/processes_spec.rb

Hide dates is there are blank on processes views.

Process blank dates

---

app/models/widget/feed.rb
spec/system/custom/welcome_page_spec.rb

Show all published budgets on welcome page.

Show all published budgets on welcome page

---

config/locales/custom/nl/general.yml

Replace custom text

---

app/controllers/admin/poll/questions_controller.rb
config/locales/custom/nl/admin.yml
config/locales/en/admin.yml
config/locales/es/admin.yml
spec/system/admin/poll/questions_spec.rb

Change redirect when delete poll questions.

Change redirect when delete poll questions

---

config/locales/custom/nl/budgets.yml

Replace share message text

---

config/locales/custom/nl/activerecord.yml

Replace custom label for budget investment heading.

Replace custom label for budget investment heading

---

config/locales/custom/nl/budgets.yml

Replace custom texts for new investment recommendations.

Replace custom texts for new investment recommendations

---

app/views/budgets/_phases.html.erb
app/views/custom/shared/_budgets_phase_video.html.erb

Add custom video to budget phases and extract this content in a new partial.

Add custom video to budget phases

---

app/views/welcome/index.html.erb

Add custom steps partial on welcome page.

Add custom steps partial on welcome page

---

config/locales/en/activerecord.yml
config/locales/en/budgets.yml
spec/system/valuation/budget_investments_spec.rb

https://github.com/StemvanGroningen/consul/pull/112
Fix translations and specs

Fix spec and translations

---

config/locales/custom/nl/general.yml

Add translations for omniauth text.

Add translations for omniauth text

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/custom/custom.scss
app/components/admin/budgets/index_component.html.erb
app/components/budgets/ballot/investment_component.html.erb
app/components/budgets/budget_component.html.erb
app/components/budgets/groups_and_headings_component.html.erb
app/components/widget/feeds/budget_component.html.erb
app/components/widget/feeds/budget_component.rb
app/helpers/budgets_helper.rb
app/views/admin/budgets/_form.html.erb
app/views/budgets/investments/_votes.html.erb
app/views/budgets/results/show.html.erb
app/views/custom/shared/_budgets_phase_video.html.erb
app/views/debates/_debate.html.erb
config/locales/custom/nl/admin.yml
config/locales/custom/nl/budgets.yml
config/locales/custom/nl/general.yml
spec/system/budgets/ballots_spec.rb
spec/system/budgets/budgets_spec.rb
spec/system/budgets/votes_spec.rb

- Add custom translations.
- Update base styles.
- Update custom styles.
- Remove duplicated title.
- Remove duplicated icon.
- Fix image on feeds budget.
- Remove budget description on budget page.
- Do not show confirm message if user can vote in all headings.
- Do not use wysiwyg on index debate description.
- Add missing css class.
- Show heading links on finished budgets.
- Update html on admin budgets form.

Custom content for the new release

---

config/locales/custom/en/mailers.yml
config/locales/custom/nl/activerecord.yml
config/locales/custom/nl/devise_views.yml
config/locales/custom/nl/sdg.yml
config/locales/custom/nl/sdg_management.yml

- Add custom translations for SDG content. 
- Add custom translations for reset password instructions.
- Add custom text for new comment email.

Custom texts

---

app/models/site_customization/image.rb
app/views/custom/welcome/_header.html.erb
spec/system/admin/site_customization/images_spec.rb

Use header image on welcome page header.

Use header image on welcome page header

---

app/assets/stylesheets/custom/custom.scss

Fix font size on budget investments index list.

Fix font size on budget investments index list

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/custom/custom.scss

Fix word break on budget investments index list.

Fix word break on budget investments index list

---

app/assets/stylesheets/custom/custom.scss

Fix menu for small screens

---

app/components/admin/budget_headings/headings_component.html.erb
app/controllers/admin/budgets_wizard/budgets_controller.rb
app/views/valuation/budget_investments/_dossier_form.html.erb
spec/system/admin/budgets_spec.rb
spec/system/admin/budgets_wizard/budgets_spec.rb

Add missing hide money content and specs.

Add missing hide money content and specs

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/custom/custom.scss

Fix styles for headers with background images.

Fix styles for headers with background images

---

app/views/polls/questions/_question.html.erb

Add line breaker on poll question number.

Add line breaker on poll question number

---

app/views/admin/debates/show.html.erb
spec/system/admin/debates_spec.rb

Fix the link to show the comments on the admin debate view

Fix link to comments on admin view for debates

---

app/views/budgets/investments/_investment_detail.erb
app/views/custom/shared/_budgets_phase_video.html.erb
spec/system/budgets/budgets_spec.rb
spec/system/budgets/investments_spec.rb

Add link to full size images on budgets.

Add link to full size images on budgets

---

app/assets/stylesheets/custom.scss
app/views/admin/poll/polls/_form.html.erb
app/views/polls/_poll_header.html.erb
app/views/polls/show.html.erb
config/locales/en/general.yml
config/locales/es/general.yml
config/locales/nl/general.yml
spec/system/admin/poll/polls_spec.rb
spec/system/admin/translatable_spec.rb
spec/system/polls/polls_spec.rb

- Add wysiwyg to poll description and summary.
- Add custom styles for poll more info title.

Poll header

---

config/locales/custom/nl/budgets.yml
config/locales/custom/nl/verification.yml
config/locales/nl/budgets.yml

- Move supports info texts to custom keys.
- Add custom verification texts.

Replace custom keys

---

config/locales/custom/nl/budgets.yml

Add custom text for vote investments.

Add custom text for vote investments

---

app/views/shared/_subnavigation.html.erb
config/i18n-tasks.yml

Remove polls link on navigation menu.

Remove polls link on navigation menu

---

app/views/budgets/results/_results_table.html.erb

Remove duplicated budget results column.

Remove duplicated budget results column

---

app/assets/stylesheets/base.scss
app/components/admin/budgets/form/info_section_checkbox_component.html.erb
app/components/admin/budgets/form/info_section_checkbox_component.rb
app/components/admin/budgets/form/info_section_data_component.html.erb
app/components/admin/budgets/form/info_section_data_component.rb
app/components/admin/budgets/form_component.html.erb
app/components/budgets/budget_component.html.erb
app/components/budgets/info_section_component.html.erb
app/components/budgets/info_section_component.rb
app/controllers/admin/budgets_controller.rb
app/models/budget.rb
config/locales/en/activerecord.yml
config/locales/en/admin.yml
config/locales/es/activerecord.yml
config/locales/es/admin.yml
config/locales/nl/activerecord.yml
config/locales/nl/admin.yml
db/migrate/20220705172403_add_info_section_to_budgets.rb
db/schema.rb
spec/models/budget_spec.rb
spec/system/admin/budgets_spec.rb

Add budgets info section

---

app/views/shared/_admin_login_items.html.erb

Show always poll officer menu to officers.

Show always poll officer menu to officers

---

app/views/custom/polls/_poll_group.html.erb
app/views/shared/_subnavigation.html.erb
config/i18n-tasks.yml
spec/system/polls/polls_spec.rb

Change custom poll link button to Maptonnaire.

Change custom poll link button to Maptonnaire

---

app/assets/stylesheets/custom.scss

Change header font size and background position on homepage.

Change header font size and background position

---

app/views/custom/polls/_poll_group.html.erb
spec/system/polls/polls_spec.rb

Change custom poll link title to Maptionnaire.

Change custom poll link title to Maptionnaire

---

app/assets/stylesheets/custom.scss

Fix investments list word break.

Fix investments list word break

---

app/models/budget.rb
config/locales/custom/nl/budgets.yml
spec/models/budget_spec.rb

Add `created_at` order to investments.

Add created at order to investments

---

app/views/budgets/investments/_investment_show.html.erb
spec/system/budgets/investments_spec.rb

Replace investment show back link.

Replace investment show back link

---

app/controllers/management/users_controller.rb
config/initializers/devise.rb
config/locales/nl/devise_views.yml
db/dev_seeds/users.rb
db/seeds.rb
spec/factories/users.rb
spec/system/account_spec.rb
spec/system/management/users_spec.rb
spec/system/organizations_spec.rb
spec/system/registration_form_spec.rb
spec/system/sessions_spec.rb
spec/system/users_auth_spec.rb

Change minimum password length to 12 characters.

Change minimum password length to 12 characters

---

app/controllers/users/sessions_controller.rb
spec/system/welcome_spec.rb

When a user first log in, it will be redirected to the account page.

First login leads to user account page

---

Gemfile.lock
Gemfile_custom
config/schedule.rb
lib/tasks/backup.rake

- Create daily backups and store them in the cloud Mega

Create daily backups and store them in the cloud Mega

---

app/assets/stylesheets/base.scss

Reduce budget header font size on small screens.

Reduce budget header font size on small screens

---

app/assets/stylesheets/custom.scss

Adjust custom page cards height.

Adjust custom page cards height

---

config/routes.rb

Add custom route `/beweegplekmikkelhorst` to budget `id 20`.

Add custom route to budget

---

config/locales/custom/nl/activerecord.yml

Update custom budget form heading translation.

Update custom budget form heading translation

---

.github/workflows/tests.yml
app/models/budget.rb
spec/components/budgets/investments/filters_component_spec.rb
spec/models/budget_spec.rb
spec/system/budgets/investments_spec.rb

Remove budget investments unselected filter.

Remove budget investments unselected filter

---

db/migrate/20230215073305_change_default_user_notifications.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/system/comments/budget_investments_valuation_spec.rb
spec/system/emails_spec.rb

Change default user notifications.

Change default user notifications

---

app/views/devise/menu/_login_items.html.erb
config/i18n-tasks.yml
spec/support/common_actions/users.rb
spec/system/emails_spec.rb
spec/system/users_auth_spec.rb

Remove signup link on header

---

app/views/account/show.html.erb
config/i18n-tasks.yml
spec/support/common_actions/verifications.rb
spec/system/management/email_verifications_spec.rb
spec/system/polls/voter_spec.rb
spec/system/sessions_spec.rb
spec/system/verification/email_spec.rb
spec/system/verification/letter_spec.rb
spec/system/verification/level_three_verification_spec.rb
spec/system/verification/residence_spec.rb

Remove verification info on account show.

Remove verification info on account show

---

app/assets/stylesheets/custom.scss

Change form label color

---

config/locales/custom/nl/community.yml

Update community custom text

---

.github/workflows/tests.yml
config/routes.rb

Add custom routes to budgets

---

app/assets/stylesheets/custom.scss

Add custom styles to footer and links.

Add custom styles to footer and links

---

app/views/mailer/budget_investment_unfeasible.html.erb

Replace link on investment unfeasible mailer.

Replace link on investment unfeasible mailer

---

app/views/budgets/investments/_sidebar.html.erb
spec/system/budgets/investments_spec.rb

Add not logged in message on investments sidebar.

Add not logged in message on investments sidebar

---

app/views/organizations/registrations/new.html.erb

Add margin top to organizations sign up button.

Add margin top to organizations sign up button

---

config/initializers/errbit.rb

Configure airbrake as Errbit documentation says

Configure airbrake as Errbit documentation says

---

app/views/custom/shared/_budgets_links.html.erb
config/locales/custom/en/general.yml
config/locales/custom/nl/general.yml

Add custom link on budgets list.

Add custom link on budgets list

---

app/assets/stylesheets/custom.scss
app/components/budgets/investments/form_component.html.erb
app/components/debates/form_component.html.erb
app/components/proposals/form_component.html.erb
app/models/proposal.rb
config/i18n-tasks.yml
config/locales/custom/en/general.yml
config/locales/custom/nl/general.yml
config/locales/nl/general.yml
spec/components/budgets/investments/form_component_spec.rb
spec/support/common_actions.rb
spec/support/common_actions/documents.rb
spec/support/common_actions/images.rb
spec/support/common_actions/maps.rb
spec/system/budgets/investments_spec.rb
spec/system/debates_spec.rb
spec/system/emails_spec.rb
spec/system/management/proposals_spec.rb
spec/system/proposals_spec.rb
spec/system/tags/budget_investments_spec.rb
spec/system/tags/debates_spec.rb
spec/system/tags/proposals_spec.rb
spec/system/tags_spec.rb
spec/system/translatable_spec.rb

Show terms of service checkbox on forms.

Show terms of service checkbox on forms

---

app/views/budgets/show.html.erb

Remove footer on budgets show.

Remove footer on budgets show

---

app/views/custom/shared/_budgets_links.html.erb
config/locales/custom/en/general.yml
config/locales/custom/nl/general.yml

Remove custom budget menu

---

app/models/concerns/attachable.rb

Avoid error when trying to update the name of an image

Avoid error when trying to update the name of an image

---

app/assets/stylesheets/custom.scss
app/views/custom/layouts/devise.html.erb

Add custom devise layout

---

app/assets/stylesheets/_custom_settings.scss
app/assets/stylesheets/custom.scss

Replace custom colors

---

app/views/legislation/processes/_header.html.erb

Fix additional info button on legislation header. Show button only if additional info is present.

Fix additional info button on legislation header

---

app/assets/stylesheets/custom.scss

Replace homepage cards title color.

Replace homepage cards title color

---

app/assets/stylesheets/custom.scss

Replace categories color

---

app/assets/stylesheets/custom.scss
app/views/custom/layouts/_footer.html.erb
config/locales/custom/en/general.yml
config/locales/custom/nl/general.yml

Update custom footer

---

app/controllers/admin/budget_investments_controller.rb
app/views/admin/budget_investments/edit.html.erb
spec/shared/system/custom_admin_nested_documentable.rb
spec/shared/system/custom_admin_nested_imageable.rb
spec/system/custom/admin/budget_investments_spec.rb

Allow admins to include images or documents to investments.

Allow admins to include images or documents to investments

---

config/locales/en/responders.yml
spec/system/admin/budget_investments_spec.rb
spec/system/budgets/investments_spec.rb
spec/system/custom/admin/budget_investments_spec.rb

Fix a typo in the English translations

Fix translation to match the upstream source code

---

config/locales/custom/nl/budgets.yml

Update custom text

---

app/assets/stylesheets/custom.scss

Fix homepage header

---

config/locales/custom/nl/rails.yml

Add custom translations

---

app/controllers/legislation/questions_controller.rb

Change order on legislation questions comments.

Change order on legislation questions comments

---

config/routes.rb

Update custom route

---

app/views/custom/legislation/processes/_header.html.erb
spec/controllers/custom/legislation/questions_controller_spec.rb

Add missing color on custom legislation header view.

Add missing color on custom legislation header view

---

lib/capistrano/monit/conf.d/postgres.erb

Update monit configuration after server upgrade

Update monit configuration after server upgrade

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/custom.scss

Update word break CSS rule
