- config/routes.rb
- spec/features/help_page_spec.rb
- spec/features/site_customization/custom_pages_spec.rb
- spec/spec_helper.rb
- spec/support/custom_common_actions.rb
Since Groningen has a custom help page with a different slug we need to route the help page to that custom slug
> Fix error when visiting /help

- config/initializers/ckeditor.rb
Fix an issue with CKEditor in CONSUL version 1.0
In some cases, in the production environment the dialogs for links, images and tables didn't work, because these plugins were not precompiled.
> Precompile CKEditor dialog plugins

- app/models/budget.rb
- app/views/budgets/index.html.erb
- app/views/budgets/investments/_header.html.erb
- app/views/budgets/investments/_investment_show.html.erb
- app/views/budgets/investments/_sidebar.html.erb
- app/views/custom/layouts/_footer.html.erb
- config/i18n-tasks.yml
- config/initializers/social_share_button.rb
- config/locales/custom/en/budgets.yml
- config/locales/custom/nl/admin.yml
- config/locales/custom/nl/budgets.yml
- config/locales/custom/nl/devise_views.yml
- config/locales/custom/nl/general.yml
- spec/features/budgets/budgets_spec.rb
- spec/features/budgets/investments_spec.rb
- spec/features/debates_spec.rb
- spec/features/proposals_spec.rb
- spec/features/tags/budget_investments_spec.rb
- spec/models/budget_spec.rb
- Update custom texts.
- Fix aside HTML tag on the sidebar.
- Hide unused content:
- Hide unfeasible investment projects link.
- Heading price.
- Tag cloud and categories.
- Change link to heading text on budgets index.
- Disable Google+ share button.
- Add custom text on budget investments header.
- Change the order of budget investments filters menu.
> Custom texts

- app/controllers/admin/site_customization/information_texts_controller.rb
- app/controllers/application_controller.rb
- app/controllers/management/base_controller.rb
- config/initializers/application_custom.rb
- spec/features/localization_spec.rb
- spec/spec_helper.rb
- Always show English translation and avoid showing "missing translation" message
- Set locale correctly when the value in the cookies is no longer an available locale
> Ignore available locales and add English fallback

- app/assets/stylesheets/custom.scss
- app/views/custom/welcome/_feeds.html.erb
- spec/features/admin/homepage/homepage_spec.rb
- Fix participation not allowed message on comments.
- Remove budget phase description links on homepage cards.
> Fix layout bugs

- app/assets/stylesheets/custom.scss
- app/views/budgets/investments/new.html.erb
- config/locales/custom/en/budgets.yml
- config/locales/custom/nl/budgets.yml
- spec/features/budgets/investments_spec.rb
Add custom recommendations text on budget investment new form.
> Add custom recommendations text on budget investment new form

- app/assets/stylesheets/custom.scss
- app/views/custom/welcome/_header.html.erb
- Remove the header image on small screens.
- Adjust text sizes on the welcome page.
> Welcome page

- app/assets/stylesheets/custom.scss
- app/views/budgets/_phases.html.erb
- app/views/budgets/investments/_investment.html.erb
- app/views/budgets/investments/_map.html.erb
- app/views/custom/layouts/_footer.html.erb
- app/views/custom/welcome/_feeds.html.erb
- app/views/layouts/_tracking_data.html.erb
- app/views/layouts/application.html.erb
- spec/features/budgets/investments_spec.rb
- Add alt text to the logo image on the footer.
- Replace `<span>` tag to div on the welcome budget description.
- Add role main to application layout.
- Add missing content to `<meta>` tracking data tag.
- Remove empty `</p>` tag.
- Replace `frameborder="0"` with CSS.
- Avoid duplicated ids on budget investments images.
- Fix color contrast.
- Replace ul to div on budget investments map.
> Accessibility

- app/assets/stylesheets/participation.scss
- app/models/budget.rb
- app/views/budgets/investments/_investment_detail.erb
- app/views/budgets/investments/_investment_info.html.erb
- app/views/budgets/investments/_investment_show.html.erb
- config/locales/custom/en/general.yml
- config/locales/custom/nl/budgets.yml
- config/locales/custom/nl/general.yml
- config/locales/en/budgets.yml
- spec/features/budgets/investments_spec.rb
- spec/models/budget_spec.rb
- Add comment count to investments.
- Remove sidebar investment title in the show view.
- Show any investments in the selecting phase: show a sample of any type of investment instead of showing only the feasible ones.
> Budget custom content

- spec/features/admin/emails/newsletters_spec.rb
- Add missing `segment_recipient` on newsletters spec.
> Add missing segment recipient on newsletters spec

- app/helpers/budgets_helper.rb
- app/views/budgets/_supports_info.html.erb
- spec/features/budgets/budgets_spec.rb
BUG FIX
We were showing all the supports for all the budgets, now we only show the supports for the budget the user is viewing.
> Show correct total number of supports in the budget view

- app/helpers/budgets_helper.rb
- spec/features/budgets/budgets_spec.rb
Since we added the ability to remove a support, the vote was still in the database, but with a negative value. So we will only have into consideration positive votes to calculate the total amount of investments the user has supported.
> Include only positive votes in the total of supports

- spec/features/admin/emails/newsletters_spec.rb
https://github.com/StemvanGroningen/consul/pull/59
Add missing segment recipients on newsletters spec.
> Add missing segment recipients on newsletters spec

- app/assets/stylesheets/custom.scss
- app/controllers/users/confirmations_controller.rb
- app/views/devise/shared/_links.html.erb
- config/i18n-tasks.yml
- config/locales/custom/en/devise_views.yml
- config/locales/custom/nl/devise.yml
- config/locales/custom/nl/devise_views.yml
- config/locales/en/devise.yml
- config/locales/es/devise.yml
- spec/features/users_auth_spec.rb
Do not resend confirmation instructions email for already confirmed users.
Instead, we will show an alert saying that the user is already confirmed.
> Do not resend confirmation email for already confirmed users

- app/views/budgets/investments/index.html.erb
Using `@heading.name` was generating an `undefined method "name" for nil:NilClass` error when the `?heading_id?=` param was missing in the URL.
This PR removes duplicated `@heading.name` and only is render if the `@heading` param is present.
> Remove heading name on unfeasible list

- app/helpers/budget_investments_helper.rb
- app/helpers/imageables_helper.rb
- app/views/budgets/investments/_author_actions.html.erb
- spec/features/budgets/investments_spec.rb
- Remove the delete image button on budget investment.
**Before the user could remove the image in any phase, except `accepting phase`.**
**Now the user only can edit the budget investment, including the image, during the `accepting phase`.**
> Remove the delete image button on budget investment

- app/controllers/admin/stats_controller.rb
- app/controllers/stats_controller.rb
- spec/features/admin/stats_spec.rb
The statistics of the budgets in the admin panel `/admin/stats/budget_supporting?budget_id=N` show the total supports number. 
This PR adds the `vote_flag: true` attribute to ignore withdrawn supports and remove unused `@investment_votes` in the stats controller.
> Count only positive supports on admin budget stats

- app/assets/stylesheets/participation.scss
Fix share on whatsapp icon position.
> Fix share on whatsapp icon

- app/assets/stylesheets/custom.scss
- app/models/budget.rb
- app/views/custom/shared/_budgets_links.html.erb
- app/views/shared/_subnavigation.html.erb
- spec/features/budgets/budgets_spec.rb
Show open budget link on subnavigation menu.
> Budgets menu

- app/models/budget.rb
- spec/features/admin/budgets_spec.rb
Now when an admin tries to delete a budget with administrators or valuators associated an error 500 is generated.
This PR allows deleting a budget with staff assigned. 😌
> Allow to delete a budget with staff assigned

- app/models/budget.rb
- app/models/budget/group.rb
- app/models/budget/heading.rb
- spec/features/admin/budget_investments_spec.rb
- spec/features/budgets/investments_spec.rb
- spec/features/management/budget_investments_spec.rb
In the form of creating a new investment was hiding the name of the group if it had only one heading, but could be confusing to users if there are, for example, five different groups of one heading.
The solution:
- **If the budget has one group and one heading, the heading selector is hidden.**
- **If the budget has one group and more than one heading, the group name is hidden.**
- **If the budget has more than one group, the group name appears regardless of the number of headings.**
> Hide group name only on budgets with one group

- app/models/image.rb
The minimum height will still be used for validation, but the image will not be resized depending on that value. The frontend layout is designed for images with a height of 475 pixels and changing this value will make the content not to look like it should.
> Do not resize image depending on minimum height

- app/views/budgets/ballot/_ballot.html.erb
- spec/features/budgets/ballots_spec.rb
Hide group name with single heading on ballot.
>  Hide group name with single heading on ballot

- app/controllers/admin/stats_controller.rb
- spec/system/admin/stats_spec.rb
- Show only votes for headings that belongs to the current budget.
- Do not count removed votes, so the participants count and the number of votes will be the same.
> Show correct budget ballot stats

- app/models/budget/phase.rb
- spec/models/budget/phase_spec.rb
It was possible to edit an existing phase without a start or end date and it was causing the application to throw unexpected errors
Make both dates to be mandatory
> Require budget phases dates

- app/views/admin/dashboard/administrator_tasks/index.html.erb
- config/locales/custom/nl/admin.yml
- config/locales/en/admin.yml
- config/locales/es/admin.yml
- spec/system/admin/dashboard/administrator_tasks_spec.rb
Show task proposal title only if its present to avoid an error if the proposal has been deleted.
> Show task proposal title only if its present

- app/controllers/admin/budget_investments_controller.rb
- app/controllers/budgets/investments_controller.rb
- app/models/administrator.rb
- app/models/valuator.rb
- app/models/widget/feed.rb
- app/views/admin/budget_investments/_select_investment.html.erb
- app/views/budgets/investments/_header.html.erb
- app/views/budgets/results/show.html.erb
- app/views/legislation/questions/_answer_form.html.erb
- config/locales/custom/nl/budgets.yml
- config/locales/custom/nl/devise_views.yml
- config/locales/custom/nl/general.yml
- config/locales/custom/nl/legislation.yml
- spec/controllers/admin/budget_investments_controller_spec.rb
- spec/spec_helper.rb
- spec/system/admin/administrators_spec.rb
- spec/system/admin/valuators_spec.rb
- spec/system/budgets/investments_spec.rb
- spec/system/budgets/results_spec.rb
- spec/system/custom/welcome_page_spec.rb
- spec/views/admin/budget_investments/select_investment_spec.rb
- Add custom translations.
- Replace back link on investments header.
- Add br tag for legislation questions answers.
- Hide sidebar results for single heading budgets.
- Don't redirect when toggling visible to valuators.
- Allow to delete valuators that are assigned to budgets.
- Allow to delete administrators that are assigned to budgets.
- Show only open published budgets on homepage cards.
- Show assigned heading on investment show.
> Custom content

- app/models/user.rb
- spec/system/budgets/votes_spec.rb
To be able to support on a different budget heading within the same group if you have removed all the supports on the other heading.
> Support different heading if other supports were removed

- app/assets/stylesheets/admin.scss
- app/views/admin/budget_phases/_form.html.erb
The date forms have been redesigned in the latest version of CONSUL and the CSS class `.input-calendar-icon` is no longer needed.
**BEFORE**
**AFTER**
> Remove duplicated calendar icon

- app/models/budget.rb
- app/views/custom/shared/_budgets_links.html.erb
- app/views/shared/_subnavigation.html.erb
- spec/system/budgets/budgets_spec.rb
Show last open budget on budgets path. Also removes the link if there are more than one PB opened.
> Show last open budget on budgets path

- app/models/budget/phase.rb
Replace budget phase `DESCRIPTION_MAX_LENGTH` from `2000` to `4000`.
> Replace budget phase description max length

- app/assets/stylesheets/custom.scss
- app/views/legislation/annotations/_comments_box.html.erb
Fix comments box container position.
> Fix comments box container position

- app/models/concerns/measurable.rb
Increase `description_max_length` from 6000 to 7000 characters.
> Increase description max length

- app/models/budget/ballot.rb
- Error https://errors.democrateam.com/apps/5dff36a7b2aa2903f8364ae4/problems/60e6ef41b2aa29034cf29f1b
- Error https://errors.democrateam.com/apps/5dff36a7b2aa2903f8364ae4/problems/60e6c968b2aa29034cf29f10
Avoid raising error undefined method `heading' for nil:NilClass
> Avoid raising error undefined method `heading' for nil:NilClass

- Gemfile
Airbrake docs https://github.com/airbrake/airbrake#delayedjob
Add Errors from `delayed_job` also in Errbit
According to the documentation adding the line `require 'airbrake/delayed_job'` should work, but it didn't, so we changed the order that gems are loaded so we make sure `delayed_job` is always loaded before `airbrake`.
Errors are now being received in Errbit:
> Show delayed job errors on Errbit

- app/components/budgets/budget_component.html.erb
Use `original` image size instead of `large` on budget header.
> Use original image size on budget header

- app/models/budget.rb
- app/models/widget/feed.rb
- spec/system/custom/welcome_page_spec.rb
Hide valuating and finished budgets on homepage feeds.
> Hide valuating and finished budgets on homepage feeds

- app/assets/stylesheets/base.scss
- app/views/custom/legislation/processes/_process.html.erb
- spec/system/budgets/budgets_spec.rb
- spec/system/legislation/processes_spec.rb
- Fix poll message on mobile.
- Fix subnavigation menu on mobile.
- Hide phases list on mobile.
- Add links to legislation processes dates.
> Design fixes for mobile devices

- app/models/budget/phase.rb
Increase budget phase description max length from `4000` to `8000`.
> Increase budget phase description max length

- app/components/budgets/investments/form_component.html.erb
- app/controllers/budgets/investments_controller.rb
- app/models/budget/investment.rb
- app/views/budgets/investments/_investment_detail.erb
- app/views/budgets/investments/_investment_show.html.erb
- config/locales/custom/en/budgets.yml
- config/locales/custom/nl/budgets.yml
- db/migrate/20230403125448_add_author_estimation_cost_to_budget_investments.rb
- db/schema.rb
- spec/system/budgets/investments_spec.rb
Add author estimation cost to budget investments.
> Add author estimation cost to budget investments

- config/locales/nl/rails.yml
Add missing space on budgets dates.
> Add missing space on budgets dates
